import type { Metadata } from 'next'
import Header from '@/components/Header/Header'



export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function AboutLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <Header />
            {children}
        </>
    )
}
