import './globals.css'
import type { Metadata } from 'next'
import HeaderMain from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                {children}
                <Footer />
            </body>
        </html>
    )
}
